### ISSUE TITLE
Specifier deletion is unnecessarily complicated

### ISSUE THREAD

**Issue by GZhang2** [phyloref/curation-tool#11]

**Comment by gaurav** [comment]
It's always useful to include the steps taken to reproduce a bug like this and what a possible solution might be! This is particularly useful when reporting a UI issue, where it may not be obvious to the programmer why a particular behavior is unintuitive. For example:

Steps to reproduce:
1. When a phyloreference is selected, click on "Delete some specifiers".
2. Buttons to delete appear, and then do not disappear unless you click on the "Delete some specifiers" button again.

Expected behavior: some specifiers are deleted.
Observed behavior: a "specifier deletion mode" is activated, with deletion buttons displayed next to each specifier. It is not obvious how to turn "specifier deletion mode" off.

Possible fixes:
1. At the very least, the "Delete some specifiers" button should be labeled as "Turn on specifier deletion mode" and then change to "Turn off specifier deletion mode" once deletion mode is on.
2. However, a more reasonable interface would keep the specifier delete buttons turned on at all times.
