### ISSUE TITLE
Standardize and improve code style

### ISSUE THREAD

**Issue by gaurav** [phyloref/curation-tool#36]
I (try to) consistently use the same coding style in a project. In reading through the [Google Javascript style guide](https://google.github.io/styleguide/jsguide.html) and [Airbnb Javascript guide](https://github.com/airbnb/javascript), I've identified a few changes we should make:
- [x] Convert variable names from snake_case to camelCase (currently [in progress in a branch](https://github.com/phyloref/curation-tool/tree/from_snake_to_camelCase)).
- [x] Replace `throw "string"` with `throw new Error("string")`
- [x] Replace `abc(function(v) { ... })` with `abc(v => { ... })`, which will remove the requirement to [save `this`](https://github.com/airbnb/javascript#naming--self-this).
- [x] Replace object methods such as `abc: function(a) { ... }` with object method shorthands, e.g. `abc(a) { ... }`.
- [x] Move code that needs to refer to `vm` into the Vue model.
- [x] Make sure lines are not much more than 100 columns in width.
- [x] Replace concatenated strings with [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).
- [x] Replace `obj.hasOwnProperty('...')` (which we use a *lot*) with [a variable storing hasOwnProperty](https://github.com/airbnb/javascript#objects--prototype-builtins)
- [x] We might be able to simplify some code by using [object destructuring](https://github.com/airbnb/javascript#destructuring--object).
- [x] Added [trailing commas](https://github.com/airbnb/javascript#commas--dangling).
- [x] Airbnb has some [great suggestions for jQuery](https://github.com/airbnb/javascript#jquery), including
  - [x] Prefix jQuery object variables with a `$`
  - [x] Cache jQuery lookups

The following suggestions are reasonable, but I think we're fine ignoring them as long as we are consistent:
- [x] Google suggests title-casing acronyms, i.e. `testcaseAsJson` rather than `testcaseAsJSON`, but [Airbnb](https://github.com/airbnb/javascript#naming--Acronyms-and-Initialisms) and I prefer the latter. So let's always capitalize acronyms in names.
- [x] Google prefers indenting by two spaces for code blocks and by four spaces when a statement stretches across multiple lines. Airbnb suggests two spaces for both of these cases. I prefer four spaces for both these cases.

**Comment by hlapp** [comment]
💯

**Comment by hlapp** [comment]
I would quite strongly recommend to adopt [eslint](https://eslint.org). It is very powerful, used widely, and is highly configurable. The default rule set is quite strict, and prompts a lot of thought as to why one wants to ignore those rules (which, if one decides so, is easy to do, and subsequently this fact is codified).

For example, you use `obj.hasOwnProperty()` frequently. This is convenient, and fine for an application (which is not inherited from in situations that you do not control). For code that is to be used as a package or library, this is dangerous, because you don't control what `obj.hasOwnProperty` is (someone might give you an object that has had this overwritten). See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
