### ISSUE TITLE
Clade name doesn't appear at root node

### ISSUE THREAD

**Issue by GZhang2** [phyloref/curation-tool#7]
e.g., Laurasiarana

**Comment by gaurav** [comment]
It turns out that this is because PhyloTree always overwrites the root node label with the label "root". We could write our own workaround, but it might be worth it for me to learn a bit more about Phylotree.js and submit modified code to them, since we're probably going to use that library a lot. I've filed an issue with them in any case: https://github.com/veg/phylotree.js/issues/60

**Comment by gaurav** [comment]
It looks like phylotree.js fixed it at their end. I've incorporated their development version of phylotree.js in commit d2e692a. Once that commit is reviewed, this issue will be closed automatically.
